restaurant/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace restaurant.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

restaurant/Controllers/OnlineMenuController.cs
using Microsoft.AspNetCore.Mvc;
using restaurant.Data;
using restaurant.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace restaurant.Controllers
{
    public class OnlineMenuController : Controller
    {
        private readonly AppDbContext context;
        public OnlineMenuController(AppDbContext context)
        {
            this.context = context;
        }
        public IActionResult Index(int id)
        {

            dynamic mymodel = new ExpandoObject();



            mymodel.Categories = context.Categories.ToList();
            if (id == 0)
            {
                mymodel.Items = context.Items.Where(x => x.CategoryId == 1).ToList();
                if (id == 0) ViewBag.Name = "Starters";
                else ViewBag.Name = context.Categories.Find(id).Name;
            }
            else
            {
                mymodel.Items = context.Items.Where(x => x.CategoryId == id).ToList();
                ViewBag.Name = context.Categories.Find(id).Name;

            }

            //IEnumerable<Item> items = context.Items.Where(x=> x.CategoryId == c.Id);
            return View(mymodel);
        }

        
    }
}

restaurant/Controllers/SetMealController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace restaurant.Controllers
{
    public class SetMealController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

restaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="menu">
            <img src="~/Images/spicelogo.png" />
            <div class="contact">
                <p>Phone: 01939796379 | Email: hhasib181@gmail.com </p>
                <div class="menu-right">
                    <a href="#">My Account</a>
                    <a asp-action="SignUp">Sign Up</a>
                    <a asp-action="SignIn">Sign In</a>
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg> <span class="cart">0</span>
                    </a>
                </div>
            </div>

        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm nav-custom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 custom">
                        <li class="nav-item start">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="OnlineMenu" asp-action="Index">Online Menu</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="SetMeal" asp-action="Index">Set Meal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    
    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>